version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-test
    ports:
      - 5672:5672 # queue
      - 15672:15672 # web UI
    volumes:
      - ~/.docker-conf/rabbitmq/data:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log:/var/log/rabbitmq
    networks:
      - rabbitmq-test
networks:
  rabbitmq-test:
    driver: bridge
